name: my first flow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v5

        - name: Welcome Message
          run: |
            chmod +x demo.sh
            ./demo.sh

    Test-job:
        runs-on: unbuntu-latest
        steps:
        - name: Echo Msg
          run: echo "heelo testing job"

    deploy-job:
        runs-on: ubuntu-latest
        steps:
        - name: Display message
          run: echo "deploying app"

        